### ISSUE TITLE
Document nonAdobeDependencies folder

### ISSUE THREAD

**Issue by davidjgonzalez** [adobe/aio-cli-plugin-aem-cloud-service-migration#3]
I've run `aio aem-migration:repository-modernizer` and my project is converted properly, however, I have a new folder named `nonAdobeDependencies` at the root of my modernized project.

This folder is empty, but I'm curious as to what this folder is used for, and what triggers its population, with what, and what would I do with whatever is placed in here.

**Comment by ManasMaji** [comment]
Hi @davidjgonzalez! I have now updated the [Repository Modernizer doc](https://github.com/adobe/aem-cloud-service-source-migration/tree/master/packages/repository-modernizer#4-refactor-the-pom-files) to include the following info :
```
3rd party bundle dependencies which are found will be reported, please add 3rd party dependency jar files in the nonadobedependencies directory (which would serve as a local repository for 3rd party bundles). It will be included in the repository section of the parent pom.
```

**Comment by ukgaurav** [comment]
This is updated. Thanks
