### ISSUE TITLE
Support local config file lookup

### ISSUE THREAD

**Issue by bstopp** [adobe/aio-cli-plugin-aem-cloud-service-migration#5]
Expected Behaviour

As a user of this plugin, I should be able to use a config.yaml file that is local to the project which is being edited. Only having one file supported, with one configuration, means that I cannot work on multiple projects at a time and the configuration is disconnected from the source.
Actual Behaviour

Local configurations not supported

**Comment by ukgaurav** [comment]
Thanks @bstopp . https://github.com/adobe/aio-cli-plugin-aem-cloud-service-migration/pull/7
