### ISSUE TITLE
Windows Build Tools Required for Windows without Python

### ISSUE THREAD

**Issue by sreeni-b** [adobe/aio-cli-plugin-aem-cloud-service-migration#8]
### Expected Behaviour
Plugin installation happens by following the docs

### Actual Behaviour
Plugin installation does not happen if python is not installed in windows

### Reproduce Scenario (including but not limited to)
Installing migration plugin in Windows without python

#### Steps to Reproduce
1. Remove python from windows if already installed.
2. Install Node 10+
3. Install aio cli
4. Install aio-cli-plugin-aem-cloud-service-migration
We get an error regarding python error and also windows tools

#### Platform and Version
aio version - @adobe/aio-cli/6.0.0 win32-x64 node-v10.16.3

#### Logs taken while reproducing problem

The issue was fixed after running this
npm install --global --production windows-build-tools

I am not sure whether anybody has tested this. If Windows require this, then we might have to document this in the docs.

**Comment by senn** [comment]
I was having the exact same issue but the "npm install --global --production windows-build-tools" command gets stuck after printing the message "Successfully installed Python 2.7".

Afterwards I still can't install the plugin.  Same error message "Error: Could not find any Python installation to use"

**Comment by sreeni-b** [comment]
> I was having the exact same issue but the "npm install --global --production windows-build-tools" command gets stuck after printing the message "Successfully installed Python 2.7".
> 
> Afterwards I still can't install the plugin. Same error message "Error: Could not find any Python installation to use"

Try running the cmd as administrator.

**Comment by senn** [comment]
I am already running it as administrator. I have also tried running it from cmd or PowerShell but both get stuck.

```
Status from the installers:
---------- Visual Studio Build Tools ----------
Still waiting for installer log file...
------------------- Python --------------------
Successfully installed Python 2.7
```

**Comment by senn** [comment]
I added the "--vs2015" option and got it working.
Full command:
`npm install --global --production windows-build-tools --vs2015`

**Comment by sreeni-b** [comment]
> I added the "--vs2015" option and got it working. Full command: `npm install --global --production windows-build-tools --vs2015`

Great. Good to know! Thanks for the update
